// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/register": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/analytics": {
    params: {};
  };
  "/admin/crm": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/admin/notifications": {
    params: {};
  };
  "/api-docs": {
    params: {};
  };
  "/auth/activate": {
    params: {};
  };
  "/chat/:id": {
    params: {
      "id": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/crisis-resources": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/deployment-dashboard": {
    params: {};
  };
  "/donate": {
    params: {};
  };
  "/donate/success": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/feedback/:id": {
    params: {
      "id": string;
    };
  };
  "/how-it-works": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/rewards": {
    params: {};
  };
  "/safety": {
    params: {};
  };
  "/security-audit": {
    params: {};
  };
  "/seeker/dashboard": {
    params: {};
  };
  "/seeker/sessions": {
    params: {};
  };
  "/session/:id": {
    params: {
      "id": string;
    };
  };
  "/sessions": {
    params: {};
  };
  "/sessions/book": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/training": {
    params: {};
  };
  "/training/apply": {
    params: {};
  };
  "/training/dashboard": {
    params: {};
  };
  "/volunteer": {
    params: {};
  };
  "/volunteer/application": {
    params: {};
  };
  "/volunteer/dashboard": {
    params: {};
  };
  "/volunteer/sessions/create": {
    params: {};
  };
  "/volunteer-guide": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account/logout" | "/account/register" | "/account/signin" | "/account/signup" | "/admin" | "/admin/analytics" | "/admin/crm" | "/admin/dashboard" | "/admin/login" | "/admin/notifications" | "/api-docs" | "/auth/activate" | "/chat/:id" | "/contact" | "/crisis-resources" | "/dashboard" | "/deployment-dashboard" | "/donate" | "/donate/success" | "/faq" | "/feedback/:id" | "/how-it-works" | "/onboarding" | "/privacy" | "/rewards" | "/safety" | "/security-audit" | "/seeker/dashboard" | "/seeker/sessions" | "/session/:id" | "/sessions" | "/sessions/book" | "/settings" | "/terms" | "/training" | "/training/apply" | "/training/dashboard" | "/volunteer" | "/volunteer/application" | "/volunteer/dashboard" | "/volunteer/sessions/create" | "/volunteer-guide" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/register/page.jsx": {
    id: "account/register/page";
    page: "/account/register";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./admin/page.jsx": {
    id: "admin/page";
    page: "/admin";
  };
  "./admin/analytics/page.jsx": {
    id: "admin/analytics/page";
    page: "/admin/analytics";
  };
  "./admin/crm/page.jsx": {
    id: "admin/crm/page";
    page: "/admin/crm";
  };
  "./admin/dashboard/page.jsx": {
    id: "admin/dashboard/page";
    page: "/admin/dashboard";
  };
  "./admin/login/page.jsx": {
    id: "admin/login/page";
    page: "/admin/login";
  };
  "./admin/notifications/page.jsx": {
    id: "admin/notifications/page";
    page: "/admin/notifications";
  };
  "./api-docs/page.jsx": {
    id: "api-docs/page";
    page: "/api-docs";
  };
  "./auth/activate/page.jsx": {
    id: "auth/activate/page";
    page: "/auth/activate";
  };
  "./chat/[id]/page.jsx": {
    id: "chat/[id]/page";
    page: "/chat/:id";
  };
  "./contact/page.jsx": {
    id: "contact/page";
    page: "/contact";
  };
  "./crisis-resources/page.jsx": {
    id: "crisis-resources/page";
    page: "/crisis-resources";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./deployment-dashboard/page.jsx": {
    id: "deployment-dashboard/page";
    page: "/deployment-dashboard";
  };
  "./donate/page.jsx": {
    id: "donate/page";
    page: "/donate";
  };
  "./donate/success/page.jsx": {
    id: "donate/success/page";
    page: "/donate/success";
  };
  "./faq/page.jsx": {
    id: "faq/page";
    page: "/faq";
  };
  "./feedback/[id]/page.jsx": {
    id: "feedback/[id]/page";
    page: "/feedback/:id";
  };
  "./how-it-works/page.jsx": {
    id: "how-it-works/page";
    page: "/how-it-works";
  };
  "./onboarding/page.jsx": {
    id: "onboarding/page";
    page: "/onboarding";
  };
  "./privacy/page.jsx": {
    id: "privacy/page";
    page: "/privacy";
  };
  "./rewards/page.jsx": {
    id: "rewards/page";
    page: "/rewards";
  };
  "./safety/page.jsx": {
    id: "safety/page";
    page: "/safety";
  };
  "./security-audit/page.jsx": {
    id: "security-audit/page";
    page: "/security-audit";
  };
  "./seeker/dashboard/page.jsx": {
    id: "seeker/dashboard/page";
    page: "/seeker/dashboard";
  };
  "./seeker/sessions/page.jsx": {
    id: "seeker/sessions/page";
    page: "/seeker/sessions";
  };
  "./session/[id]/page.jsx": {
    id: "session/[id]/page";
    page: "/session/:id";
  };
  "./sessions/page.jsx": {
    id: "sessions/page";
    page: "/sessions";
  };
  "./sessions/book/page.jsx": {
    id: "sessions/book/page";
    page: "/sessions/book";
  };
  "./settings/page.jsx": {
    id: "settings/page";
    page: "/settings";
  };
  "./terms/page.jsx": {
    id: "terms/page";
    page: "/terms";
  };
  "./training/page.jsx": {
    id: "training/page";
    page: "/training";
  };
  "./training/apply/page.jsx": {
    id: "training/apply/page";
    page: "/training/apply";
  };
  "./training/dashboard/page.jsx": {
    id: "training/dashboard/page";
    page: "/training/dashboard";
  };
  "./volunteer/page.jsx": {
    id: "volunteer/page";
    page: "/volunteer";
  };
  "./volunteer/application/page.jsx": {
    id: "volunteer/application/page";
    page: "/volunteer/application";
  };
  "./volunteer/dashboard/page.jsx": {
    id: "volunteer/dashboard/page";
    page: "/volunteer/dashboard";
  };
  "./volunteer/sessions/create/page.jsx": {
    id: "volunteer/sessions/create/page";
    page: "/volunteer/sessions/create";
  };
  "./volunteer-guide/page.jsx": {
    id: "volunteer-guide/page";
    page: "/volunteer-guide";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};